import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from './page.module.css'

import Header from "@/components/Header";

import { BasketProvider } from '@/context/Basket/BasketProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <BasketProvider>
            <Header/>
            {children}
          </BasketProvider>
        </main>
      </body>
    </html>
  )
}
