# NOTE: Ran out of time to correctly set up Vercel deployment, leaving here to outline how I approached it

# name: Deploy Vercel Preview

# on:
#   push:
#     branches:
#       - '**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'
#           cache: 'yarn'

#       - name: Install dependencies
#         run: yarn install

#       - name: Build project
#         run: yarn build

#       - name: Deploy to Vercel (Preview)
#         run: npx vercel --token=${{ secrets.VERCEL_TOKEN }}
